name: shm

on: [pull_request, workflow_dispatch]

jobs:
  shm:
    runs-on: ubuntu-latest
    env:
      path: shm/build
    steps:
    - name: Check out code
      uses: actions/checkout@master
      with:
        ref: shm2
    - name: Create build directory
      run: mkdir ${{ env.path }}
    - name: Compile
      working-directory: ${{ env.path }}
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: ${{ env.path }}
      run: ctest -V
